builds:
  - binary: cobra_cli_app
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/limesten/cobra_cli_app/cmd.GoBlueprintVersion={{.Version}}

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
